# numpy入门
* numpy的基本结构为ndarray

In [1]:
import numpy as np

## 1、创建ndarray
**元素必须都为同一类型**

### 1.1、python列表创建

In [16]:
# 一维列表
n1 = np.array([1,2,3,4])
print(n1)

# 二维列表
n2 = np.array([[1,2],[3,4],[5,6]])
print(n2)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]


### 1.2、类python的range

In [19]:
n3 = np.arange(1,10,1)
print(n3)

[1 2 3 4 5 6 7 8 9]


### 1.3、numpy随机数rand创建

In [48]:
# 用法
# rand(x1,x2,x3,x4...) 获取0到1之间的随机数
# 创建数组维度的规律:
# 传递n个参数，则创建n维度的数组

# 创建一维数组0-1之间的数 10个 
n4 = np.random.rand(10)
print(n4)

# 创建二维数组0-1之间的数 3*3个 
n5 = np.random.rand(3,3)
print(n5)

# 创建三维数组0-1之间的数 3*3*3个 
n6 = np.random.rand(3,3,3)
print(n6)

[0.00581634 0.34869473 0.3010849  0.71116374 0.74301093 0.5845235
 0.74038311 0.84666557 0.01927934 0.7563881 ]
[[0.32643492 0.18538836 0.35962334]
 [0.69526837 0.22795072 0.0746945 ]
 [0.04907491 0.11368963 0.72611962]]
[[[0.58165935 0.93712148 0.75541019]
  [0.78098055 0.69562587 0.07660965]
  [0.15390547 0.34432854 0.33784257]]

 [[0.13503733 0.56854798 0.004365  ]
  [0.69436104 0.12537007 0.95640332]
  [0.69544242 0.07046559 0.24190895]]

 [[0.71735982 0.1506691  0.01765332]
  [0.29394892 0.70406062 0.72624761]
  [0.9226147  0.11992261 0.62506653]]]


### 1.4、numpy随机数random

In [46]:
# 用法
# random(size=None) 获取0到1之间的随机数
# size 为 ndarray维度 (x) 为一维 
#                     (x,y) 为二维
#                     (x,y,z) 为三维

# 创建一维数组0-1之间的数 3个 
n7 = np.random.random((3))
print(n7)

# 创建二维数组0-1之间的数 2*2个 
n8 = np.random.random((2,2))
print(n8)

# 创建三维数组0-1之间的数 2*2*2个 
n9 = np.random.random((2,2,2))
print(n9)

[0.78991192 0.54374545 0.85208757]
[[0.83488675 0.26050857]
 [0.44216496 0.91449046]]
[[[0.92774499 0.0582584 ]
  [0.061889   0.68864903]]

 [[0.70107364 0.64670368]
  [0.13876994 0.78705911]]]


### 1.5、numpy随机数randint

In [44]:
# 用法
# randint(low, high=None, size=None, dtype='l')
# low 为开始整形值
# high 为 结尾整形值
# size 为 ndarray维度 (x) 为一维 
#                     (x,y) 为二维
#                     (x,y,z) 为三维

# 创建一维整形数组 3个
n10 = np.random.randint(1,10,(3))
print(n10)

# 创建二维整形数组 2*2个
n11 = np.random.randint(1,10,(2,2))
print(n11)

# 创建三维整形数组 2*2*2个
n12 = np.random.randint(1,10,(2,2,2))
print(n12)

[9 2 1]
[[7 1]
 [3 1]]
[[[7 3]
  [1 6]]

 [[5 8]
  [1 4]]]


In [51]:
# 用法
# randn(x1,x2,x3,x4...) 获取满足正态分布的数
# 创建数组维度的规律:
# 传递n个参数，则创建n维度的数组

# 创建一维数组 10个 
n13 = np.random.randn(10)
print(n4)

# 创建二维数组 3*3个 
n14 = np.random.randn(3,3)
print(n5)

# 创建三维数组 3*3*3个 
n15 = np.random.randn(3,3,3)
print(n6)

[0.00581634 0.34869473 0.3010849  0.71116374 0.74301093 0.5845235
 0.74038311 0.84666557 0.01927934 0.7563881 ]
[[0.32643492 0.18538836 0.35962334]
 [0.69526837 0.22795072 0.0746945 ]
 [0.04907491 0.11368963 0.72611962]]
[[[0.58165935 0.93712148 0.75541019]
  [0.78098055 0.69562587 0.07660965]
  [0.15390547 0.34432854 0.33784257]]

 [[0.13503733 0.56854798 0.004365  ]
  [0.69436104 0.12537007 0.95640332]
  [0.69544242 0.07046559 0.24190895]]

 [[0.71735982 0.1506691  0.01765332]
  [0.29394892 0.70406062 0.72624761]
  [0.9226147  0.11992261 0.62506653]]]


### 1.6、zeros和ones
**zeros 则创建元素都为0的n维数组**

**ones 则创建元素都为1的n维数组**

In [57]:
# zeros(size)
# size 为 ndarray维度 (x) 为一维 
#                     (x,y) 为二维
#                     (x,y,z) 为三维

no1 = np.zeros(10)
print(no1)

# ones(size)
# size 为 ndarray维度 (x) 为一维 
#                     (x,y) 为二维
#                     (x,y,z) 为三维
no2 = np.ones((2))
print(no2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1.]


## 2、ndarray属性

In [59]:
# 打印类型
print(no2.dtype)

# 打印维度
print(no2.ndim)

# 打印维度形状
print(no2.shape)

float64
1
(2,)
