# 一、numpy文件输入输出

In [1]:
import numpy as np

## 1、二进制格式保存

In [10]:
arr = np.arange(10)
# 将数组保存成文件，文件后缀为.npy
np.save('arr',arr)

# 载入文件
arr = np.load('arr.npy')
print(arr)

# 将多个数组保存进文件
np.savez('arrs',a=arr,b=arr)

# 载入文件
arrs = np.load('arrs.npz')
print(arrs['a'])
print(arrs['b'])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## 2、txt文件
* csv本质上也是txt文本文件，因此这里用txt文件为例

In [25]:
file_name = 'test.txt'
# test.txt文件格式如下：
# a,b,c
# d,e,f

# 由于loadtxt默认载入的是float，因此这里类型转为str字符
arr = np.loadtxt(file_name,delimiter=',',dtype=str)
print(arr)

# 文件保存
np.savetxt('new_test.txt',arr,encoding='utf-8',fmt='%s')

[['a' 'b' 'c']
 ['d' 'e' 'f']]
