# numpy索引与切片操作

In [1]:
import numpy as np

In [8]:
# 创建一维数组
n1 = np.random.randint(1,10,(10))

# 创建二维数组
n2 = np.random.randint(1,10,(3,3))

# 创建三维数组
n3 = np.random.randint(1,10,(3,3,3))
print(n1)
print(n2)
print(n3)

[5 8 3 2 1 9 5 4 2 2]
[[8 9 6]
 [6 7 8]
 [7 4 7]]
[[[4 2 2]
  [3 7 7]
  [8 5 8]]

 [[5 1 1]
  [2 2 8]
  [3 3 1]]

 [[1 8 3]
  [8 6 9]
  [7 1 7]]]


## 1、索引操作
**索引值从0开始**

In [17]:
#指定索引值

# 一维数组n1 第三个
print(n1[2])

# 二维数组n2 第三行第二列
print(n2[2][1])

# 三维数组n3 z轴第二层的平面，第二行第二列
print(n3[1][1][1])

print("等价写法")
# 等价写法
print(n1[2])
print(n2[2,1])
print(n3[1,1,1])

# 理解等价写法的作用
# 这种写法是用逗号进行隔开各个维度, 这里只谈二维以上
# [x,y] 则指向 第x行第y列的值
# [z,x,y] 则指向 立体第z层的这个平面的第x行第y列的值

3
4
2
等价写法
3
4
2


## 2、切片操作
**冒号:则代表所有**

In [47]:
# 获取一维数组所有值
print(n1[:])

# 获取一维数组n1的第一、二个元素
print(n1[0:2])

# 翻转
print(n1[::-1])

# 获取二维数组所有值
print(n2[:])

# 获取二维数组第一、二行的所有元素
print(n2[0:2])

# 获取二维数组所有行第二列的所有元素
print(n2[:,1])

# 获取二维数组所有行第一、二列的所有元素
print(n2[:,0:2])

[5 8 3 2 1 9 5 4 2 2]
[5 8]
[2 2 4 5 9 1 2 3 8 5]
[[8 9 6]
 [6 7 8]
 [7 4 7]]
[[8 9 6]
 [6 7 8]]
[9 7 4]
[[8 9]
 [6 7]
 [7 4]]


In [67]:
# 获取三维数组所有元素
print(n3[:])

# 获取z轴第一、二层所有元素
print(n3[0:2])

# 获取z轴第一、二层的平面的第一、二行
print(n3[0:2,:2])

# 获取z轴第一、二层的平面的第一、二行的第二列
print(n3[0:2,:2,1])

[[[4 2 2]
  [3 7 7]
  [8 5 8]]

 [[5 1 1]
  [2 2 8]
  [3 3 1]]

 [[1 8 3]
  [8 6 9]
  [7 1 7]]]
[[[4 2 2]
  [3 7 7]
  [8 5 8]]

 [[5 1 1]
  [2 2 8]
  [3 3 1]]]
[[[4 2 2]
  [3 7 7]]

 [[5 1 1]
  [2 2 8]]]
[[2 7]
 [1 2]]


**-切片时，[x:y]表示左闭右开。即左边的x可以获取到，而右边只能获取比y小的值**

## 3、引用操作

In [72]:
# 赋值操作
nn1 = n1[:3]
print(n1)
print(nn1)

nn1[0] = 6
print(n1)
print(nn1)

# 根据打印的信息可以知道，n1索引值为0的值跟着nn1的值变化而变化
# 那要解决切片导致的引用问题，可以使用copy

nn2 = n1[:3].copy()
print(n1)
print(nn2)

nn2[0] = 7
print(n1)
print(nn2)

[6 8 3 2 1 9 5 4 2 2]
[6 8 3]
[6 8 3 2 1 9 5 4 2 2]
[6 8 3]
[6 8 3 2 1 9 5 4 2 2]
[6 8 3]
[6 8 3 2 1 9 5 4 2 2]
[7 8 3]
