# numpy常用函数

In [1]:
import numpy as np

## 1、形状
**reshape、ravel、T**

In [32]:
# reshape(size)
# size 为 ndarray维度 (x) 为一维 
#                     (x,y) 为二维
#                     (x,y,z) 为三维

n1 = np.arange(8)
print(n1)

# 转变为二维数组 2*4
n2 = n1.reshape((2,4))
print(n2)

# 转变为三维数组 2*2*2
n3 = n1.reshape((2,2,2))
print(n3)

# 拼接
n4 = np.arange(5,13).reshape((2,4))
# 横向
print(np.hstack((n2,n4)))
# 竖向
print(np.vstack((n2,n4)))

# 层叠
print(np.stack((n2,n4)))


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[ 0  1  2  3  5  6  7  8]
 [ 4  5  6  7  9 10 11 12]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 5  6  7  8]
  [ 9 10 11 12]]]


In [45]:
n1 = np.arange(8)
# 横切
print(np.hsplit(n1,2))
print(np.hsplit(n1,4))

# 竖切
n2 = n1.reshape((2,4))
print(n2)
print(np.vsplit(n2,2))

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]
[[0 1 2 3]
 [4 5 6 7]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]


In [14]:
# 把多维数组拉平
display(n2.ravel())

# 横列转置
display(n2.T)

array([0, 1, 2, 3, 4, 5, 6, 7])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

## 2、排序、重复

In [61]:
n1 = np.arange(4)
print(n1)

# 重复
print(np.tile(n1,(2,2)))

# 一维数组排序
n2 = np.random.randint(1,10,(5))
print(n2)
# 排序
print(np.sort(n2))

# 二维数组排序
n3 = np.random.randint(1,10,(2,2))
print(n3)
# 排序 竖向
print(np.sort(n3,axis=0))
# 排序 横向
print(np.sort(n3,axis=1))

[0 1 2 3]
[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]
[6 1 7 1 5]
[1 1 5 6 7]
[[8 2]
 [3 2]]
[[3 2]
 [8 2]]
[[2 8]
 [2 3]]


## 2、其它

In [7]:
# 线性代数
# 从2到5之间取100个数
np.linspace(2,5,100)

array([2.        , 2.03030303, 2.06060606, 2.09090909, 2.12121212,
       2.15151515, 2.18181818, 2.21212121, 2.24242424, 2.27272727,
       2.3030303 , 2.33333333, 2.36363636, 2.39393939, 2.42424242,
       2.45454545, 2.48484848, 2.51515152, 2.54545455, 2.57575758,
       2.60606061, 2.63636364, 2.66666667, 2.6969697 , 2.72727273,
       2.75757576, 2.78787879, 2.81818182, 2.84848485, 2.87878788,
       2.90909091, 2.93939394, 2.96969697, 3.        , 3.03030303,
       3.06060606, 3.09090909, 3.12121212, 3.15151515, 3.18181818,
       3.21212121, 3.24242424, 3.27272727, 3.3030303 , 3.33333333,
       3.36363636, 3.39393939, 3.42424242, 3.45454545, 3.48484848,
       3.51515152, 3.54545455, 3.57575758, 3.60606061, 3.63636364,
       3.66666667, 3.6969697 , 3.72727273, 3.75757576, 3.78787879,
       3.81818182, 3.84848485, 3.87878788, 3.90909091, 3.93939394,
       3.96969697, 4.        , 4.03030303, 4.06060606, 4.09090909,
       4.12121212, 4.15151515, 4.18181818, 4.21212121, 4.24242